import 'product.dart';

class ProductsRepository {
  static List<Product> loadProducts(Category category) {
    const allProducts = <Product>[
      Product(
        category: Category.accessories,
        id: 0,
        isFeatured: true,
        name: 'Vagabond sack',
        price: 120,
        assetName: 'vagabond-sack.jpg',
        assetPackage: 'shrine_images',
      ),
      Product(
        category: Category.accessories,
        id: 1,
        isFeatured: true,
        name: 'Stella sunglasses',
        price: 58,
        assetName: 'stella-sunglasses.jpg',
        assetPackage: 'shrine_images',
      ),
      Product(
        category: Category.accessories,
        id: 2,
        isFeatured: false,
        name: 'Whitney belt',
        price: 35,
        assetName: 'whitney-belt.jpg',
        assetPackage: 'shrine_images',
      ),
      Product(
        category: Category.accessories,
        id: 3,
        isFeatured: true,
        name: 'Garden strand',
        price: 98,
        assetName: 'garden-strand.jpg',
        assetPackage: 'shrine_images',
      ),
      Product(
        category: Category.accessories,
        id: 4,
        isFeatured: false,
        name: 'Strut earrings',
        price: 34,
        assetName: 'strut-earrings.jpg',
        assetPackage: 'shrine_images',
      ),
      Product(
        category: Category.accessories,
        id: 5,
        isFeatured: false,
        name: 'Varsity socks',
        price: 12,
        assetName: 'varsity-socks.jpg',
        assetPackage: 'shrine_images',
      ),
      Product(
        category: Category.accessories,
        id: 6,
        isFeatured: false,
        name: 'Weave key ring',
        price: 16,
        assetName: 'weave-key-ring.jpg',
        assetPackage: 'shrine_images',
      ),
      Product(
        category: Category.clothing,
        id: 7,
        isFeatured: true,
        name: 'Gatsby hat',
        price: 40,
        assetName: 'gatsby-hat.jpg',
        assetPackage: 'shrine_images',
      ),
      Product(
        category: Category.clothing,
        id: 8,
        isFeatured: true,
        name: 'Shrug bag',
        price: 198,
        assetName: 'shrug-bag.jpg',
        assetPackage: 'shrine_images',
      ),
      Product(
        category: Category.clothing,
        id: 9,
        isFeatured: true,
        name: 'Gilt desk trio',
        price: 58,
        assetName: 'gilt-desk-trio.jpg',
        assetPackage: 'shrine_images',
      ),
      Product(
        category: Category.clothing,
        id: 10,
        isFeatured: false,
        name: 'Copper wire rack',
        price: 18,
        assetName: 'copper-wire-rack.jpg',
        assetPackage: 'shrine_images',
      ),
      Product(
        category: Category.clothing,
        id: 11,
        isFeatured: false,
        name: 'Soothe ceramic set',
        price: 28,
        assetName: 'soothe-ceramic-set.jpg',
        assetPackage: 'shrine_images',
      ),
      Product(
        category: Category.clothing,
        id: 12,
        isFeatured: false,
        name: 'Hurrahs tea set',
        price: 34,
        assetName: 'hurrahs-tea-set.jpg',
        assetPackage: 'shrine_images',
      ),
      Product(
        category: Category.clothing,
        id: 13,
        isFeatured: true,
        name: 'Blue stone mug',
        price: 18,
        assetName: 'blue-stone-mug.jpg',
        assetPackage: 'shrine_images',
      ),
      Product(
        category: Category.home,
        id: 14,
        isFeatured: true,
        name: 'Rainwater tray',
        price: 27,
        assetName: 'rainwater-tray.jpg',
        assetPackage: 'shrine_images',
      ),
      Product(
        category: Category.home,
        id: 15,
        isFeatured: true,
        name: 'Chambray napkins',
        price: 16,
        assetName: 'chambray-napkins.jpg',
        assetPackage: 'shrine_images',
      ),
      Product(
        category: Category.home,
        id: 16,
        isFeatured: true,
        name: 'Succulent planters',
        price: 16,
        assetName: 'succulent-planters.jpg',
        assetPackage: 'shrine_images',
      ),
      Product(
        category: Category.home,
        id: 17,
        isFeatured: false,
        name: 'Quartet table',
        price: 175,
        assetName: 'quartet-table.jpg',
        assetPackage: 'shrine_images',
      ),
      Product(
        category: Category.home,
        id: 18,
        isFeatured: true,
        name: 'Kitchen quattro',
        price: 129,
        assetName: 'kitchen-quattro.jpg',
        assetPackage: 'shrine_images',
      ),
    ];
    if (category == Category.all) {
      return allProducts;
    } else {
      return allProducts.where((p) => p.category == category).toList();
    }
  }
}
